# Site settings
title: Wynne Blog
SEOTitle: 郑玮妍的博客 | Wynne Zheng Blog
header-img: https://ws3.sinaimg.cn/large/006tKfTcgy1fqgt74o60lj318g0b442s.jpg
email: yanniekv@gmail.com
description: "You really can change the world if you care enough."
keyword: "Wynne, Zheng Blog, 郑玮妍的博客, zhengweiyan, yannie"
url: "http://zhengweiyan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhengweiyan/zhengweiyan.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I quote others only in order the better to express myself."
sidebar-avatar: https://ws1.sinaimg.cn/large/006tKfTcgy1fqgtc3f92uj31b60wagpy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     1694120584
zhihu_username:     yanniezheng
github_username:    zhengweiyan
facebook_username:  100006741249892
#jianshu_username:
#twitter_username:



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4eb106518a072df7f7f5                           #生成的clientID
  clientSecret: 13e7495617488642bf44e6e0577cd70c75f4a009    #生成的clientSecret
  repo: zhengweiyan.github.io    #仓库名称
  owner: zhengweiyan    #github用户名
  admin: zhengweiyan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: e070029f47a9cc1657a23d6b8262c6b4
# Google Analytics
ga_track_id: 'UA-117745574-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "zwy",
        href: "http://123.207.232.68/"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
